Add tag field to alert, asset, dashboard and function models.
splightplatform/splight-lib-python pull request #455
Opened 2024-09-26 15:47 UTC by gbaudino-splight

2024-09-26 15:57 UTC, smartinellimarco requested changes
Use ResourceSummary not Tag

2024-10-01 19:20 UTC, smartinellimarco approved these changes

2024-10-01 19:26 UTC, marianogaragiola approved these changes

2024-10-02 09:33 UTC, francozacco approved these changes

2024-10-14 19:13 UTC, closed without merging